name: Validate JSON Schema

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON against Schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'compatibility.json'             
          schema: 'schema.json'